"""Home page: what Smart Crop Care does, how the modules work together, and Try now."""

import streamlit as st

from src.context import get_session_context
from src.ui import choose_location

STEPS = [
    (":material/upload:", "Upload a leaf", "A clear photo of one leaf of a supported crop."),
    (":material/eco:", "Disease detection",
     "A ResNet50 image model identifies the possible disease and how confident it is."),
    (":material/compost:", "Recommended crop care",
     "Fertilizer and treatment advice for the predicted disease, looked up in the project's "
     "recommendation table (not generated by the image model)."),
    (":material/partly_cloudy_day:", "Weather context",
     "Current weather and forecast for your location, as extra context for spraying and "
     "irrigation. Weather never changes the disease prediction."),
    (":material/newspaper:", "Live farmer news",
     "Current agriculture news from Indian publishers: schemes, MSP and markets, crop "
     "disease, weather and farming technology. News is information only."),
    (":material/smart_toy:", "Ask the assistant",
     "An AI assistant explains the combined result in plain language and answers "
     "follow-up questions, using only what the app knows."),
]

st.markdown("#### One system for leaf diagnosis, crop-care advice, local weather and news")
st.markdown("Upload a photo of a leaf and get the likely disease, fertilizer and treatment "
            "advice, the weather for your farm, and an assistant to answer your questions. "
            "Every part shares the same **crop context**, so the result follows you through "
            "the app.")

if st.button("Try now", type="primary", icon=":material/arrow_forward:", key="home_try_now"):
    st.switch_page("app_pages/disease_detection.py")

st.subheader("Your farm location", icon=":material/location_on:")
context = get_session_context()
with st.container(border=True):
    status = st.empty()                     # filled after the picker, so it is up to date
    has_location = context.has_weather
    with st.expander("Change location" if has_location else "Set your location",
                     expanded=not has_location):
        # Saved in the shared crop context: the dashboard and assistant use its weather.
        location = choose_location("home")
    if location is not None:
        status.markdown(f":material/check_circle: Location: **{location.label}**  \n"
                        "The dashboard and the assistant will use the weather for this place.")
        st.page_link("app_pages/weather.py", label="See the full 7-day forecast",
                     icon=":material/partly_cloudy_day:")
    else:
        status.caption("Set your location so the dashboard can show local weather for "
                       "spraying and irrigation decisions. It is optional.")

st.subheader("How it works", icon=":material/route:")
for i, (icon, title, text) in enumerate(STEPS, start=1):
    with st.container(border=True):
        st.markdown(f"{icon} **{i}. {title}**  \n{text}")

if context.has_disease or context.has_weather:
    st.subheader("Your current session", icon=":material/history:")
    parts = []
    if context.has_disease:
        parts.append(f"Latest result: **{context.crop} - {context.disease}** "
                     f"({context.confidence:.0%} confidence)")
    if context.has_weather:
        parts.append(f"Location: **{context.weather['location']['name']}**")
    st.markdown("  \n".join(parts))
    with st.container(horizontal=True):
        if context.has_disease and st.button("Back to the dashboard", icon=":material/dashboard:"):
            st.switch_page("app_pages/disease_detection.py")
        if st.button("Ask the assistant", icon=":material/smart_toy:", key="home_ask"):
            st.switch_page("app_pages/assistant.py")

st.caption("Smart Crop Care gives general guidance to support decisions. It does not replace "
           "a qualified agricultural professional.")
